### PR TITLE
Let libc.so be live-patchable

### PR DESCRIPTION
**Pull request by inconstante**
See individual commit messages for the rationale.

### CODE REVIEW

**Comment by lvwr** [comment]
Mind explaining why this is needed?

**Comment by inconstante** [comment]
> Mind explaining why this is needed?

Sure! :)

`__libc_start_main` was going through the library entrance tracking routine (`__ulp_entry`), but it never returns (well, it returns after main returns, of course; but during the regular execution of the process, you could say that it never does). So, libc.so is always thought to be _entered_, which means that the thread-local counters never get update (see https://github.com/SUSE/libpulp/blob/master/lib/trm.S#L94-L107), which further means that even though we are able to apply a live-patch, it never gets used.

**Comment by inconstante** [comment]
Or do you mean the `get_symtab` becomes `get_dynsym` part? If so, it is because the target-libraries could be stripped, but now that you asked, it feels weird, because I could run the post-processing tool right after linking, i.e. way before packaging tools do any stripping. As a matter of fact, I actually did that in OBS, so I'm not so sure about the first patch, now.

**Comment by lvwr** [comment]
> > Mind explaining why this is needed?
> 
> Sure! :)
> 
> `__libc_start_main` was going through the library entrance tracking routine (`__ulp_entry`), but it never returns (well, it returns after main returns, of course; but, during the regular execution of the process, you could say that it never does). So, libc.so is always thought to be _entered_, which means that the thread-local counters never get update (see https://github.com/SUSE/libpulp/blob/master/lib/trm.S#L94-L107), which further means that even though we are able to apply a live-patch, it never gets used.

makes total sense. tks for the details.

**Comment by lvwr** [comment]
> Or do you mean the `get_symtab` becomes `get_dynsym` part? If so, it is because the target-libraries could be stripped, but now that you asked, it feels weird, because I could run the post-processing tool right after linking, i.e. way before packaging tools do any stripping. As a matter of fact, I actually did that in OBS, so I'm not so sure about the first patch, now.
> 
> I'll double check this.

TBH, I was more concerned about the explanation you gave in the first explanation. Regarding get_dynsym/get_symtab, I don't have any input. Whatever works is fine with me. Originally we considered that debug/symtab information would always be available, but of course, this assumption may have changed in time since I stopped working on libpulp.

**Comment by inconstante** [comment]
Thanks for your review! S2

**Pull request merged**
