### PR TITLE
Add a coding style and fix it across all files?

### PR DESCRIPTION
**Pull request by inconstante**
This is a bit controversial, I know...

The project has accumulated different coding styles across the years, and a large part of the blame is on me. I'd like to see this fixed and, although I know (and very much agree) that white-space changes suck, I think that it won't cause the usual problems if we do it now, specially because we don't have stable branches, yet.

It feels like "now or never" to me.

Objections?

### CODE REVIEW

**Comment by lvwr** [comment]
I'm not generally comfortable with all the coding style proposed (for example, I would prefer function arguments to be aligned through line breaks). That said, I don't have any objection to the patch and agree that the earlier a coding-style is defined, the better. Since you took the baton (and since you are the maintainer of everything now), I think your preferences should be prioritized at this point.

Looks good to me.

**Comment by inconstante** [comment]
> for example, I would prefer function arguments to be aligned through line breaks.

Could you give an example? I'm having a little bit of trouble to understand what you mean.

**Comment by inconstante** [comment]
I'm asking because I don't really have strong opinions on any of these stuff (I went for what I'm used to, which is basically GNU style without the spaces-becomes-TABs thing, which, more often than not, leads to more discrepancies), and because most of these options are fairly easy to code in .clang-format.

**Comment by lvwr** [comment]
I misread the diff. You were actually fixing one case where the alignment was not correct (add_dependency in tools/packer.h). Ignore my comment and feel free to go ahead with the changes. And I like that you want to keep the spaces/tabs thing out of the style as I agree that it is a great source of confusion.

**Pull request merged**
